[package]
name = "candystore"
version = "1.1.0"
edition = "2024"
license = "Apache-2.0"
keywords = ["key-value", "database", "persistent", "store", "rocksdb"]
description = "A lean, efficient and fast persistent in-process key-value store"
repository = "https://github.com/sweet-security/candystore"

[dependencies]
crc16-ibm3740-fast = "0.5.0"
fslock = "0.2.1"
libc = "0.2.183"
memmap2 = "0.9.10"
num_cpus = "1.17.0"
parking_lot = "0.12.5"
postcard = { version = "1.1.3", default-features = false, features = [
    "use-std",
] }
serde = { version = "1", features = ["derive"] }
simd-itertools = "0.3.0"
siphasher = "1.0.2"
smallvec = { version = "1.15.1", features = ["write"] }
thiserror = "2.0.18"
uuid = "1.18.1"
zerocopy = { version = "0.8.47", features = ["derive"] }

[dev-dependencies]
proptest = "1.10.0"
tempfile = "3"
rand = "0.10.2"

[features]
whitebox-testing = []
