[package]
name = "candystore"
version = "0.6.0"
edition = "2024"

[dependencies]
crc16-ibm3740-fast = "0.5.0"
databuf = "0.5.0"
fslock = "0.2.1"
memmap2 = "0.9.10"
num_cpus = "1.17.0"
parking_lot = "0.12.5"
simd-itertools = "0.3.0"
siphasher = "1.0.2"
smallvec = { version = "1.15.1", features = ["write"] }
thiserror = "2.0.18"
uuid = "1.18.1"
zerocopy = { version = "0.8.47", features = ["derive"] }

[dev-dependencies]
proptest = "1.10.0"
tempfile = "3"
rand = "0.10.0"
libc = "0.2.183"
