name: Linux

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: uname -a; cargo build

      - name: Run simple example
        run: RUST_BACKTRACE=1 cargo run --example simple
      - name: Run multithreaded example
        run: RUST_BACKTRACE=1 cargo run --example multithreaded
      - name: Run lists example
        run: RUST_BACKTRACE=1 cargo run --example lists
      - name: Run typed example
        run: RUST_BACKTRACE=1 cargo run --example typed

      - name: Run tests (debug)
        run: RUST_BACKTRACE=1 cargo test -- --nocapture
      - name: Run tests (release)
        run: RUST_BACKTRACE=1 cargo test --release -- --nocapture
